package api.poja.io.repository.model.enums;

import static api.poja.io.repository.model.enums.ApplicationImportStatus.FAILED;
import static api.poja.io.repository.model.enums.ApplicationImportStatus.IN_PROGRESS;
import static api.poja.io.repository.model.enums.ApplicationImportStatus.SUCCESSFUL;

public enum ApplicationImportStateStatus {
  APPLICATION_LANGUAGE_VERIFICATION_IN_PROGRESS,
  APPLICATION_LANGUAGE_VERIFICATION_FAILED,
  APPLICATION_LANGUAGE_VERIFICATION_SUCCESSFUL,
  BUILD_TOOL_VERIFICATION_IN_PROGRESS,
  BUILD_TOOL_VERIFICATION_FAILED,
  BUILD_TOOL_VERIFICATION_SUCCESSFUL,
  PRE_TRANSFORMATION_TEST_RUN_VERIFICATION_IN_PROGRESS,
  PRE_TRANSFORMATION_TEST_RUN_VERIFICATION_FAILED,
  PRE_TRANSFORMATION_TEST_RUN_VERIFICATION_SUCCESSFUL,
  CONVERSION_TO_GRADLE_IN_PROGRESS,
  CONVERSION_TO_GRADLE_FAILED,
  CONVERSION_TO_GRADLE_SUCCESSFUL,
  GRADLE_BUILD_FILE_CONFLICTS_RESOLUTION_IN_PROGRESS,
  GRADLE_BUILD_FILE_CONFLICTS_RESOLUTION_FAILED,
  GRADLE_BUILD_FILE_CONFLICTS_RESOLVED,
  POJA_CONF_GENERATION_IN_PROGRESS,
  POJA_CONF_GENERATED,
  POJA_CONF_GENERATION_FAILED,
  CODE_GENERATION_IN_PROGRESS,
  GENERATED_CODE_INTEGRATION_IN_PROGRESS,
  GENERATED_CODE_INTEGRATION_FAILED,
  GENERATED_CODE_INTEGRATED,
  CODE_FORMATTING_IN_PROGRESS,
  CODE_FORMATTING_FAILED,
  CODE_FORMATTING_SUCCESSFUL,
  POST_TRANSFORMATION_TEST_RUN_VERIFICATION_IN_PROGRESS,
  POST_TRANSFORMATION_TEST_RUN_VERIFICATION_FAILED,
  POST_TRANSFORMATION_TEST_RUN_VERIFICATION_SUCCESSFUL,
  TEST_PING_ENDPOINT_IN_PROGRESS,
  TEST_PING_ENDPOINT_FAILED,
  TEST_PING_ENDPOINT_SUCCESSFUL,
  APPLICATION_SET_UP_IN_PROGRESS,
  APPLICATION_SET_UP_FAILED,
  APPLICATION_SET_UP_SUCCESSFUL;

  public ApplicationImportStatus toImportStatus() {
    return switch (this) {
      case APPLICATION_LANGUAGE_VERIFICATION_FAILED,
              BUILD_TOOL_VERIFICATION_FAILED,
              CONVERSION_TO_GRADLE_FAILED,
              GRADLE_BUILD_FILE_CONFLICTS_RESOLUTION_FAILED,
              POJA_CONF_GENERATION_FAILED,
              GENERATED_CODE_INTEGRATION_FAILED,
              CODE_FORMATTING_FAILED,
              PRE_TRANSFORMATION_TEST_RUN_VERIFICATION_FAILED,
              POST_TRANSFORMATION_TEST_RUN_VERIFICATION_FAILED,
              TEST_PING_ENDPOINT_FAILED,
              APPLICATION_SET_UP_FAILED ->
          FAILED;
      case APPLICATION_SET_UP_SUCCESSFUL -> SUCCESSFUL;
      default -> IN_PROGRESS;
    };
  }
}
