spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.flyway.locations=classpath:/db/migration

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.leak-detection-threshold=600000
spring.threads.virtual.enabled=true
target.account.execution.role.arn=arn:aws:iam::000000000000:role/dummy-role
aws.account.id=000000000000
aws.region=eu-west-3
aws.s3.bucket=dummy-bucket
aws.eventBridge.bus=dummy-bus
app.pem.bucket.key=dummy-key

env=dev

beta.users=[]
beta.max.user.orgs.per.user=10
beta.user.app.threshold=10

e2e.user.id=00000000-0000-0000-0000-000000000000
e2e.max.apps.per.user=10
e2e.max.orgs.per.user=10

exchange.rate.eur.usd=1
exchange.rate.usd.eur=1

github.api.baseuri=https://api.github.com
github.appid=0
github.client.id=dummy
github.client.secret=dummy
github.redirect.uri=http://localhost:8080/callback
github.token.url=https://github.com/login/oauth/access_token

mailjet.api.key=dummy
mailjet.api.secret=dummy
mailjet.api.sender.email=test@example.com
mailjet.templateid.accountcreated=0

max.allowed.inactivity.days=365
max.apps.per.user=10
max.orgs.per.user=10
max.premium.subscribers=1000

org.app.invitation.base.url=http://localhost:8080

poja.console.base.url=http://localhost:8080
poja.sam.api.key=dummy
poja.sam.api.uri=http://localhost:8080

private.beta.test=false

sentry.dsn=
sentry.environment=dev
pricing.free.tier=0.00

stripe.api.key=dummy

user.suspension.grace.period=30
platform.mode=SAAS
apps.envs.networking={}
spring.profiles.active=dev